# Generated by Django 5.1.3 on 2024-11-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegismailapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appissue',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='appissue',
            name='last_reported',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='appissue',
            name='occurrence_count',
            field=models.IntegerField(default=1),
        ),
    ]
