# Generated by Django 5.1.3 on 2024-11-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegismailapp', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='securityeventlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
