# Generated by Django 5.1.3 on 2024-11-30 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegismailapp', '0005_testmodel_securityeventlog_ip_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthcredentials',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('yahoo', 'Yahoo'), ('microsoft', 'Microsoft')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
