# Generated by Django 5.1.3 on 2024-12-02 10:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegismailapp', '0006_alter_oauthcredentials_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppIssueCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crash_count', models.IntegerField(default=0)),
                ('login_problem_count', models.IntegerField(default=0)),
                ('data_syncing_issue_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='appissue',
            name='last_reported',
        ),
        migrations.AddField(
            model_name='appissue',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appissue',
            name='issue_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='appissue',
            name='occurrence_count',
            field=models.IntegerField(default=0),
        ),
    ]
